---
title: PowerShell Profile & Functions
author: ~
date: '2018-04-12'
slug: powershell-profile
categories: [PowerShell]
output:
  blogdown::html_page:
    # toc: true
    # toc_depth: 1
    number_sections: true
---

For those unfamiliar, the PowerShell profile (`Microsoft.Powershell_profile.ps1`) is the Windows PowerShell equivalent to the Linux and Mac OS `.bashrc` file, which loads when the terminal starts and allows user to save functions, aliases, and general shell settings between sessions. [How-To Geek has a good article](https://www.howtogeek.com/50236/customizing-your-powershell-profile/) that covers how to set up a basic PowerShell profile, which I recommend reading before moving forward. All the code below can go in your PS Profile in any order, but I'll present it in the order that makes the most sense to me.

# General Terminal Setup

Like many, I prefer dark themes in all the programs I use, when available, and PowerShell is no exception. Your PowerShell profile gives you the option to tweak many UI parameters of your terminal window, including font and background colors, window size, and the window title (demonstrated below).

```powershell
$Shell = $Host.UI.RawUI
$shell.BackgroundColor = "Black"
$shell.ForegroundColor = "White"

$size = $Shell.WindowSize
$size.width = 80
$size.height = 25

$host.ui.RawUI.WindowTitle = "Beep Boop Terminal"
```

# PowerShell Path

While most Windows-based developers are familiar with adding variables to their system PATH via System Properties, there are some directories that I only want PowerShell, not the whole computer, to index As such, we'll append our PowerShell environment's `Path` with the directories where our scripts reside.

```powershell
$env:Path += ";C:\Users\Ryan\Documents\WindowsPowerShell"
```

# Aliases

PowerShell [already utilizes a lot of aliases](https://ss64.com/ps/) to make the transition from bash simpler -- familiar commands like `ls`, `mkdir`, and `cd` are available out of the box, and much easier to remember than their PowerShell names even for users who are unfamiliar with bash (for reference, those names are `Get-ChildItem`, `New-Item -Type folder`, and `Set-Location`). Within our PowerShell Profile, we can also make aliases for either native PowerShell commands, or, as I've done, to open programs via the terminal. Some programs, like VSCode (`code`), have existing aliases you can use to call them from PowerShell, but here are some that I frequently use.

```powershell
	new-item alias:np -value "C:\Program Files (x86)\Notepad++\notepad++.exe"
	new-item alias:vim -value "C:\Program Files (x86)\Vim\vim80\vim.exe"
```

# Functions

The real benefit of having a PowerShell profile is being able to write down all the brilliant functions you've written (or copied from Stack Overflow) to use months down the road! Here are some examples of various function types that I regularly use.

## Size and Number of Files by Extension

This function lists the total number and size (in MB) of all files with the same extension in a directory and all child directories. Equivalent to a MySQL `SELECT Extension, COUNT(Extension), SUM(Size) FROM ls GROUP BY Extension`.

```powershell
Function Get-FilesByType
{
	Get-ChildItem -Path $directory -Recurse |
	Where-Object { !$_.PSIsContainer } | Group-Object Extension |
	Select-Object @{n="Extension";e={$_.Name -replace '^\.'}},
	  @{n="Size (MB)";e={[math]::Round((($_.Group | Measure-Object Length -Sum).Sum / 1MB), 2)}}, Count
}
```

## Short Prompt

Changes the command-prompt to display on the current directory, not the full directory path. Doesn't have to be called, runs at startup.

```powershell
Function prompt
{
  $p = Split-Path -leaf -path (Get-Location)
  "$p> "
}
```

## Shortcut to Directory

Changes directory to a specified location, pretty simple.  

```powershell
Function projects
{
  cd D:\data\lab\code\
}
```

## List User-Defined Functions

Returns a list of all the custom functions you've defined.

```powershell
Function List-Functions
{
	Get-ChildItem function:\
}
```

## Edit PowerShell Profile

Finally, this command opens your PowerShell Profile with NotePad++ (assumes that alias is defined as above).

```powershell
Function Edit-Profile
{
  np $profile
}
```